// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ2KPzoo-NW2afb7PNkTKyKsF3KB6aypM',
    appId: '1:785624414692:web:3c5b5d3b7013e17d2c2ff1',
    messagingSenderId: '785624414692',
    projectId: 'untitled-c2dbb',
    authDomain: 'untitled-c2dbb.firebaseapp.com',
    storageBucket: 'untitled-c2dbb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvlpjzQBBqLD9vtILGUPbKs3qKh-rU67E',
    appId: '1:785624414692:android:4b23db1e532dffce2c2ff1',
    messagingSenderId: '785624414692',
    projectId: 'untitled-c2dbb',
    storageBucket: 'untitled-c2dbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeSrik0Bdq4M-yoZ9utUqfagJR4rF6w4Q',
    appId: '1:785624414692:ios:c87eef579ddf46ce2c2ff1',
    messagingSenderId: '785624414692',
    projectId: 'untitled-c2dbb',
    storageBucket: 'untitled-c2dbb.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeSrik0Bdq4M-yoZ9utUqfagJR4rF6w4Q',
    appId: '1:785624414692:ios:7c9c50256d546d4f2c2ff1',
    messagingSenderId: '785624414692',
    projectId: 'untitled-c2dbb',
    storageBucket: 'untitled-c2dbb.appspot.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}

// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart';
//
// // ...
//
// await Firebase.initializeApp(
// options: DefaultFirebaseOptions.currentPlatform,
// );